# Generated by Django 4.0 on 2022-07-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/classification/images/', verbose_name='图片')),
                ('result', models.CharField(choices=[(0, 'airplane'), (1, 'automobile'), (2, 'bird'), (3, 'cat'), (4, 'deer'), (5, 'dog'), (6, 'frog'), (7, 'horse'), (8, 'ship'), (9, 'truck')], max_length=100, verbose_name='分类结果')),
                ('probability', models.FloatField(verbose_name='概率')),
                ('probability_list', models.CharField(max_length=100, verbose_name='概率列表')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ipaddress', models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP地址')),
            ],
            options={
                'verbose_name': '预测分类记录',
                'verbose_name_plural': '预测分类记录',
                'db_table': 'tb_classification_record',
            },
        ),
    ]
