# Generated by Django 4.0.6 on 2022-07-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificationrecord',
            name='probability_list',
            field=models.CharField(max_length=300, verbose_name='概率列表'),
        ),
    ]
